In [ ]:
1. Write a Python Program to Add Two Matrices?

In [4]:
import numpy as np
a1 = np.array([[100,200,300],[400,500,600],[700,800,900]])
a2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
a1+a2

array([[110, 211, 312],
       [413, 514, 615],
       [716, 817, 918]])

In [ ]:
2. Write a Python Program to Multiply Two Matrices?

In [10]:
a1 = np.array([[1,2],[4,5],[7,8]])
a2 = np.array([[10,11,12],[13,14,15]])
a3 = np.zeros((a1.shape[0],a2.shape[1]))

sum = 0
n = 0
for i in range(a1.shape[0]):
    for j in range(a2.shape[1]):
        for k in range(a2.shape[0]):
            sum = sum + (a1[i][k] * a2[k][j] )
        a3[i][j] = sum
        sum = 0
print(f"Multiplication of matrix is \n \n {a1} \n and \n {a2} \n  is \n {a3}")

Multiplication of matrix is 
 
 [[1 2]
 [4 5]
 [7 8]] 
 and 
 [[10 11 12]
 [13 14 15]] 
  is 
 [[ 36.  39.  42.]
 [105. 114. 123.]
 [174. 189. 204.]]


In [5]:
a1 = np.array([[100,200,300],[400,500,600],[700,800,900]])
a2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
a1*a2

array([[ 1000,  2200,  3600],
       [ 5200,  7000,  9000],
       [11200, 13600, 16200]])

In [ ]:
3. Write a Python Program to Transpose a Matrix?

In [6]:
a1 = np.array([[100,200,300],[400,500,600],[700,800,900]])
a1.T

array([[100, 400, 700],
       [200, 500, 800],
       [300, 600, 900]])

In [8]:
a = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])

b = np.zeros((a.shape[0],a.shape[1]))
print(f"Input matrix is \n \n {a}")

print("Transpose of matrix is \n ")

for i in range(a.shape[0]):
    b[:,i] = a[i,:]
    
print(b)

Input matrix is 
 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Transpose of matrix is 
 
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [ ]:
4. Write a Python Program to Sort Words in Alphabetic Order?

In [11]:
test = "ineuron"
result = ''.join(sorted(test))
print(f"Input World is : {test}")
print(f"Output word in Sorted Aphabetical Order is :{result}")

Input World is : ineuron
Output word in Sorted Aphabetical Order is :einnoru


In [ ]:
5. Write a Python Program to Remove Punctuation From a String?

In [12]:
teststring = "I'm learning Python. It's easy & simple to understand"

punct = '''!@#$%^&*()-[]{};:'"\,<>./?_~'''
optstring = ""
for i in teststring:
    if i not in punct:
        optstring = optstring + i
        
print(f"Input String with punctuation is \n {teststring} \n ")
print(f"Output String without punctuation is \n {optstring} \n ")

Input String with punctuation is 
 I'm learning Python. It's easy & simple to understand 
 
Output String without punctuation is 
 Im learning Python Its easy  simple to understand 
 
